// SquadData.ts
import { ImageSourcePropType } from "react-native";

export interface PlayerStats {
  primary: string;
  secondary: string;
  passAcc: string;
  keyMetric: string;
}

export interface Player {
  id: string;
  name: string;
  number: string;
  countryCode: string;
  country: string;
  position: string;
  age: number;
  bio: string;
  stats: PlayerStats;
  image: ImageSourcePropType;
  status?: "Starter" | "Bench" | "Injured";
}

export interface SquadSection {
  title: string;
  data: Player[];
}

export const SQUAD_DATA: SquadSection[] = [
  {
    title: "GOALKEEPERS",
    data: [
      {
        id: "1",
        name: "Manuel Neuer",
        number: "1",
        countryCode: "GER",
        country: "Germany",
        position: "Goalkeeper",
        age: 39,
        status: "Starter",
        bio: "The undisputed greatest sweeper-keeper in football history. Manuel Neuer redefined the goalkeeping position with his aggressive positioning and unmatched distribution.",
        stats: {
          primary: "14",
          secondary: "82",
          passAcc: "88%",
          keyMetric: "78% Save",
        },
        image: require("../assets/images/1.png"),
      },
      {
        id: "2",
        name: "Sven Ulreich",
        number: "26",
        countryCode: "GER",
        country: "Germany",
        position: "Goalkeeper",
        status: "Bench",
        age: 36,
        bio: "A deeply reliable deputy between the sticks. Sven Ulreich has stepped up in massive Champions League and Bundesliga moments whenever called upon.",
        stats: {
          primary: "4",
          secondary: "18",
          passAcc: "81%",
          keyMetric: "71% Save",
        },
        image: require("../assets/images/26.png"),
      },
      {
        id: "3",
        name: "Jonas Urbig",
        number: "40",
        countryCode: "GER",
        country: "Germany",
        position: "Goalkeeper",
        status: "Starter",
        age: 22,
        bio: "One of Germany's brightest young goalkeeping talents, developing under the wing of Manuel Neuer.",
        stats: {
          primary: "0",
          secondary: "0",
          passAcc: "0%",
          keyMetric: "N/A",
        },
        image: require("../assets/images/40.png"),
      },
    ],
  },
  {
    title: "DEFENDERS",
    data: [
      {
        id: "6",
        name: "Dayot Upamecano",
        number: "2",
        countryCode: "FRA",
        country: "France",
        position: "Center Back",
        status: "Starter",
        age: 27,
        bio: "A physical powerhouse with excellent ball-playing ability. Upamecano is central to Bayern's high defensive line.",
        stats: {
          primary: "2",
          secondary: "1",
          passAcc: "92%",
          keyMetric: "6.1 Tackles",
        },
        image: require("../assets/images/2.png"),
      },
      {
        id: "7",
        name: "Kim Min-jae",
        number: "3",
        countryCode: "KOR",
        country: "South Korea",
        position: "Center Back",
        age: 29,
        status: "Bench",
        bio: "Known as 'The Monster', Min-jae brings relentless aggression, aerial dominance, and elite recovery speed to the backline.",
        stats: {
          primary: "3",
          secondary: "0",
          passAcc: "94%",
          keyMetric: "7.2 Clears",
        },
        image: require("../assets/images/3.png"),
      },
      {
        id: "8",
        name: "Jonathan Tah",
        number: "4",
        countryCode: "GER",
        country: "Germany",
        position: "Center Back",
        age: 30,
        status: "Starter",
        bio: "An imposing defensive wall. Tah brings vital Bundesliga experience and leadership to the heart of the defense.",
        stats: {
          primary: "4",
          secondary: "1",
          passAcc: "91%",
          keyMetric: "82% Aerial",
        },
        image: require("../assets/images/4.png"),
      },
      {
        id: "9",
        name: "Hiroki Ito",
        number: "21",
        countryCode: "JPN",
        country: "Japan",
        position: "Center Back",
        age: 26,
        status: "Starter",
        bio: "A versatile, left-footed defender capable of playing centrally or at full-back, known for his incisive forward passing.",
        stats: {
          primary: "1",
          secondary: "3",
          passAcc: "89%",
          keyMetric: "5.4 Intercepts",
        },
        image: require("../assets/images/21.png"),
      },
      {
        id: "10",
        name: "Raphaël Guerreiro",
        number: "22",
        countryCode: "POR",
        country: "Portugal",
        position: "Left Back",
        age: 32,
        status: "Bench",
        bio: "A highly technical left-back who can comfortably invert into midfield, providing elite chance creation from deep.",
        stats: {
          primary: "3",
          secondary: "7",
          passAcc: "88%",
          keyMetric: "2.1 Chances",
        },
        image: require("../assets/images/22.png"),
      },
      {
        id: "11",
        name: "Josip Stanišić",
        number: "44",
        status: "Starter",
        countryCode: "CRO",
        country: "Croatia",
        position: "Right Back",
        age: 25,
        bio: "A homegrown defensive specialist. Stanišić provides incredibly intelligent, tactically disciplined performances across the backline.",
        stats: {
          primary: "1",
          secondary: "2",
          passAcc: "87%",
          keyMetric: "4.4 Tackles",
        },
        image: require("../assets/images/44.png"),
      },
      {
        id: "12",
        name: "Alphonso Davies",
        number: "19",
        status: "Starter",
        countryCode: "CAN",
        country: "Canada",
        position: "Left Back",
        age: 25,
        bio: "The 'Roadrunner'. Davies possesses world-class pace and dribbling, making him a terrifying attacking outlet down the left flank.",
        stats: {
          primary: "2",
          secondary: "8",
          passAcc: "86%",
          keyMetric: "3.2 Dribbles",
        },
        image: require("../assets/images/19.png"),
      },
    ],
  },
  {
    title: "MIDFIELDERS",
    data: [
      {
        id: "13",
        name: "Joshua Kimmich",
        number: "6",
        countryCode: "GER",
        country: "Germany",
        position: "Defensive Midfielder",
        age: 31,
        status: "Starter",
        bio: "The heartbeat of Bayern Munich. Kimmich dictates the tempo of the game with his elite passing range and fierce competitive mentality.",
        stats: {
          primary: "4",
          secondary: "12",
          passAcc: "91%",
          keyMetric: "94.2 Touches",
        },
        image: require("../assets/images/6.png"),
      },
      {
        id: "14",
        name: "Leon Goretzka",
        number: "8",
        countryCode: "GER",
        country: "Germany",
        position: "Central Midfielder",
        age: 31,
        status: "Bench",
        bio: "A true box-to-box powerhouse. Goretzka combines physical dominance with a brilliant instinct for arriving late in the penalty area.",
        stats: {
          primary: "6",
          secondary: "5",
          passAcc: "86%",
          keyMetric: "1.8 Shots",
        },
        image: require("../assets/images/8.png"),
      },
      {
        id: "15",
        name: "Jamal Musiala",
        number: "10",
        countryCode: "GER",
        country: "Germany",
        position: "Attacking Midfielder",
        age: 23,
        status: "Starter",
        bio: "Jamal Musiala is one of the most exciting talents in world football. Known for his incredible close control and dribbling ability, 'Bambi' consistently delivers match-winning performances.",
        stats: {
          primary: "12",
          secondary: "8",
          passAcc: "89%",
          keyMetric: "4.2 Dribbles",
        },
        image: require("../assets/images/10.png"),
      },
      {
        id: "16",
        name: "Konrad Laimer",
        number: "27",
        countryCode: "AUT",
        country: "Austria",
        position: "Central Midfielder",
        age: 28,
        status: "Starter",
        bio: "A relentless pressing machine. Laimer is the engine room, disrupting opposition attacks and transitioning the ball with speed.",
        stats: {
          primary: "2",
          secondary: "3",
          passAcc: "85%",
          keyMetric: "4.1 Tackles",
        },
        image: require("../assets/images/27.png"),
      },
      {
        id: "17",
        name: "Aleksandar Pavlović",
        number: "45",
        countryCode: "GER",
        country: "Germany",
        position: "Defensive Midfielder",
        age: 21,
        status: "Starter",
        bio: "A breakout academy star. Pavlović plays with maturity beyond his years, offering calm, precise distribution from the base of midfield.",
        stats: {
          primary: "2",
          secondary: "4",
          passAcc: "93%",
          keyMetric: "68.4 Passes",
        },
        image: require("../assets/images/45.png"),
      },
      {
        id: "18",
        name: "Tom Bischof",
        number: "20",
        countryCode: "GER",
        country: "Germany",
        position: "Attacking Midfielder",
        age: 20,
        status: "Bench",
        bio: "A highly technical creative midfielder with exceptional vision and dead-ball delivery.",
        stats: {
          primary: "1",
          secondary: "2",
          passAcc: "84%",
          keyMetric: "1.1 Chances",
        },
        image: require("../assets/images/20.png"),
      },
      {
        id: "19",
        name: "Lennart Karl",
        number: "42",
        countryCode: "GER",
        country: "Germany",
        position: "Midfielder",
        age: 19,
        status: "Starter",
        bio: "A promising youth prospect looking to make his mark on the first team.",
        stats: {
          primary: "0",
          secondary: "0",
          passAcc: "88%",
          keyMetric: "N/A",
        },
        image: require("../assets/images/42.png"),
      },
    ],
  },
  {
    title: "FORWARDS",
    data: [
      {
        id: "20",
        name: "Harry Kane",
        number: "9",
        countryCode: "ENG",
        country: "England",
        position: "Center-Forward",
        age: 32,
        status: "Starter",
        bio: "A world-class finisher and elite playmaker. Kane is the focal point of Bayern's attack, dropping deep to link play before arriving to finish.",
        stats: {
          primary: "38",
          secondary: "11",
          passAcc: "78%",
          keyMetric: "3.8 Shots",
        },
        image: require("../assets/images/9.png"),
      },
      {
        id: "21",
        name: "Serge Gnabry",
        number: "7",
        countryCode: "GER",
        country: "Germany",
        position: "Winger",
        age: 30,
        status: "Starter",
        bio: "A clinical, two-footed winger. Gnabry is known for his explosive pace and ability to score spectacular goals from tight angles.",
        stats: {
          primary: "10",
          secondary: "6",
          passAcc: "81%",
          keyMetric: "2.1 Shots",
        },
        image: require("../assets/images/7.png"),
      },
      {
        id: "22",
        name: "Michael Olise",
        number: "17",
        countryCode: "FRA",
        country: "France",
        position: "Winger",
        age: 24,
        status: "Starter",
        bio: "A devastatingly creative right winger. Olise brings flair, incredible set-piece delivery, and highly unpredictable 1v1 ability.",
        stats: {
          primary: "9",
          secondary: "14",
          passAcc: "83%",
          keyMetric: "3.4 Chances",
        },
        image: require("../assets/images/17.png"),
      },
      {
        id: "23",
        name: "Luis Díaz",
        number: "14",
        countryCode: "COL",
        country: "Colombia",
        position: "Winger",
        age: 29,
        status: "Starter",
        bio: "An electrifying addition to the frontline. Díaz brings relentless energy, direct running, and a constant threat cutting inside from the left.",
        stats: {
          primary: "11",
          secondary: "7",
          passAcc: "82%",
          keyMetric: "3.1 Dribbles",
        },
        image: require("../assets/images/14.png"),
      },
      {
        id: "24",
        name: "Nicolas Jackson",
        number: "11",
        countryCode: "SEN",
        country: "Senegal",
        position: "Forward",
        age: 24,
        status: "Bench",
        bio: "A dynamic, fast-paced forward capable of leading the line or playing off the shoulder of the defense.",
        stats: {
          primary: "14",
          secondary: "4",
          passAcc: "76%",
          keyMetric: "2.4 Shots",
        },
        image: require("../assets/images/11.png"),
      },
    ],
  },
  {
    title: "COACH",
    data: [
      {
        id: "25",
        name: "Vincent Kompany",
        number: "0",
        countryCode: "BEL",
        country: "Belgium",
        position: "Manager",
        age: 40,
        status: "Starter",
        bio: "Bringing a modern, aggressive, and possession-based philosophy to Munich. Kompany demands high intensity and tactical fluidity from his squad.",
        stats: {
          primary: "72%",
          secondary: "3",
          passAcc: "N/A",
          keyMetric: "Win Rate",
        },
        image: require("../assets/images/vk.png"),
      },
    ],
  },
];
